# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: >
  (?x)^(
    third_party/.*|
    .*\.pb.*\.go
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: \.pvt\.
      - id: end-of-file-fixer
        exclude: \.pvt\.
      - id: check-yaml
        exclude: \.pvt\.
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: \.pvt\.
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
        args: [--timeout=5m]
    # - id: go-cyclo
    # args: [-over=20]
  - repo: local
    hooks:
      - id: codegen
        name: generate code
        pass_filenames: false
        language: system
        always_run: true
        entry: >
          sh -c '
            make codegen &&
            git add oomagent/codegen sdk/python/src/oomstore/codegen
          '
